import { HttpException, HttpStatus } from '@nestjs/common';

export enum TenantErrorCode {
  TENANT_REQUIRED = 'TENANT_REQUIRED',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  TENANT_EXPIRED = 'TENANT_EXPIRED',
  INVALID_TENANT_CONTEXT = 'INVALID_TENANT_CONTEXT',
  MODULE_NOT_ENABLED = 'MODULE_NOT_ENABLED',
  MODULE_ACCESS_CHECK_FAILED = 'MODULE_ACCESS_CHECK_FAILED',
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
  PLAN_INACTIVE = 'PLAN_INACTIVE',
  INVALID_PLAN = 'INVALID_PLAN',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_ALREADY_EXISTS = 'SUBSCRIPTION_ALREADY_EXISTS',
  INVALID_BILLING_CYCLE = 'INVALID_BILLING_CYCLE',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED',
  INVALID_PAYMENT_STATUS = 'INVALID_PAYMENT_STATUS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_UNAUTHORIZED = 'PAYMENT_UNAUTHORIZED',
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  INVOICE_ALREADY_PAID = 'INVOICE_ALREADY_PAID',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_SUSPENDED = 'SUBSCRIPTION_SUSPENDED',
  SUBSCRIPTION_ACCESS_RESTRICTED = 'SUBSCRIPTION_ACCESS_RESTRICTED',
  EMPLOYEE_LIMIT_EXCEEDED = 'EMPLOYEE_LIMIT_EXCEEDED',
  HR_USER_LIMIT_EXCEEDED = 'HR_USER_LIMIT_EXCEEDED',
  ADMIN_USER_LIMIT_EXCEEDED = 'ADMIN_USER_LIMIT_EXCEEDED',
  STORAGE_LIMIT_EXCEEDED = 'STORAGE_LIMIT_EXCEEDED',
  API_LIMIT_EXCEEDED = 'API_LIMIT_EXCEEDED',
  INVALID_BILLING_ACTION = 'INVALID_BILLING_ACTION',
  PAYMENT_PROVIDER_NOT_FOUND = 'PAYMENT_PROVIDER_NOT_FOUND',
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT_PROVIDER_UNAVAILABLE',
  PAYMENT_PROVIDER_ERROR = 'PAYMENT_PROVIDER_ERROR',
  PAYMENT_PROVIDER_INVALID_RESPONSE = 'PAYMENT_PROVIDER_INVALID_RESPONSE',
}

export class TenantException extends HttpException {
  constructor(
    public readonly code: TenantErrorCode,
    message: string,
    status: HttpStatus = HttpStatus.BAD_REQUEST,
  ) {
    super(
      {
        statusCode: status,
        errorCode: code,
        message,
        timestamp: new Date().toISOString(),
      },
      status,
    );
  }
}
